<!DOCTYPE HTML>
<html lang="en-US">
<head>
	<meta charset="UTF-8">
	<title>Conduit End-User License Agreement</title>
	<link rel="stylesheet" href="/css/service_page.css">
	<script type="text/javascript" src="/js/jquery.js"></script>
	<script type="text/javascript" src="/js/jquery.ifixpng.js"></script>
	<script type="text/javascript">$(document).ready(function(){ $('.png').ifixpng(); });</script>
</head>

<body>
<div class="all">

	<div class="clear">&nbsp;</div>

	<div class="logo">
		<a href="/"><img src="/images/logo-pdfssoftware.png" class="png" alt="" /></a>
	</div>

	<div class="dashboard-wrapper">

		<div class="dashboard-top"></div>

		<div class="dashboard">

		<h1>Conduit End-User License Agreement</h1>
    <br>

    Welcome
    <br><br>
    PLEASE READ CAREFULLY THE TERMS AND CONDITIONS OF THIS END USER LICENSE AGREEMENT (THE "EULA" or “AGREEMENT”) BEFORE DOWNLOADING, INSTALLING OR USING ANY SOFTWARE PROVIDED BY CONDUIT LTD. ("CONDUIT" OR “WE”) OR ENABLING ANY SUCH SOFTWARE (COLLECTIVELY, THE "CONDUIT SOFTWARE"). THE CONDUIT SOFTWARE DOES NOT INCLUDE THIRD-PARTY SOFTWARE (AS DEFINED IN SECTION 2 BELOW) OR OPEN SOURCE SOFTWARE (AS DEFINED IN SECTION 4 BELOW). THIS IS A LEGAL AGREEMENT BETWEEN CONDUIT AND YOU.  THIS EULA, THE CONDUIT PRIVACY POLICIES AND THE CONTENT SHARING TERMS OF SERVICE (AVAILABLE AT <a href="http://www.conduit.com/">http://www.conduit.com/</a>), ALL OF WHICH ARE INCORPORATED HEREIN BY REFERENCE (AND COLLECTIVELY REFERRED TO HEREUNDER AS THE “EULA”), GOVERN YOUR ACCESS TO AND USE OF THE CONDUIT SOFTWARE.  In the event there is a contradiction between the terms in this Agreement and the Content Sharing Terms of Service, the terms of this Agreement will prevail. In the event there is a contradiction between this EULA and the privacy policy, the privacy policy will control.<br><br>

    Conduit is willing to license the Conduit Software to you only on the condition that you accept all the terms contained in this EULA. By selecting the "Next" button (or similar language provided by us) or by downloading, installing or using the Conduit Software, you acknowledge and agree that you have read and understand this EULA and accept all of its terms. <br><br>

    We recommend that you print out or save a local copy of this EULA for your records.  If you agree to this EULA on behalf of another person or legal entity including, without limitation, another business, you represent and warrant that you have the authority to bind that entity to this EULA and your agreement to this EULA will be treated as the agreement of the entity. In that event, "you" and "your" will refer and apply to that entity. If you do not accept this EULA in its entirety, then Conduit is unwilling to license the Conduit Software to you and you may not access or use the Conduit Software. Any use of the Conduit Software by you under these circumstances will be considered a violation of Intellectual property laws and may subject you to civil and/or criminal penalties. <br><br>

    <ol>
        1.	<b>Modification.</b><br>
        Conduit reserves the right to modify and/or change any of the terms and conditions of this EULA at any time and without prior notice. If Conduit materially modifies this EULA it will post the updated EULA as part of a drop down menu from the Conduit Software via a hyperlink or by other reasonable means now known or hereafter developed. Conduit will also update the "Last Updated Date" at the end of this Agreement. By continuing to use the Conduit Software after Conduit has posted a modification of this EULA, you agree to be bound by the modified EULA. If the modified EULA is not acceptable to you, your only recourse is to uninstall the Conduit Software. This Agreement will also govern any software upgrades and/or updates provided by Conduit that upgrade and/or supplement the Conduit Software, unless such upgrades and/or updates are accompanied by a separate license, in which case the terms of that separate license will. <br><br>

        2.<b> The Conduit Software and Third Party Software. </b><br>
        <ol><b>2.1.</b>	Conduit provides a platform that allows third parties to customize the Conduit Software and distribute it to you (“Publishers”).  Following your agreement to this EULA, the Conduit Software is installed on your computer. The Conduit Software may include web search box(es) and other features.  Such installed search features are further detailed in section 3 below. In addition, the installation of the Conduit Software may enable Conduit to access, use and collect a variety of information, both personal and non-personal, regarding your Browser, your browsing habits, and information about your computer (additional information is further detailed in section 3 below).   </ol><br><br>
        <ol><b>2.2.</b>	The Publishers customization of the Conduit Software may take the form of adding data, information, links, web pages, images, software and code, text, photos, audio or video sounds, and/or visual works and components to the Conduit Software (collectively “Third Party Software”), and then  distributing it to you (the “Customized Software”). Conduit does not have control of and does not take any responsibility for anything a Publisher adds to the Conduit Software, which may include without limitation, naming the Conduit Software. Some Publishers may distribute the Customized Software as stand-alone software and some may distribute it as part of a package containing the Customized Software bundled with Third Party Software. Third Party Software is the responsibility of the Publishers and not Conduit. Some Third Party Software and/or Customized Software may contain Cookies or other tracking mechanisms. Sometimes the Third Party Software may be presented in an iFrame in your Browser.  When this happens, because you are interacting directly with the Third Party Software this interaction is considered a first party interaction.  Therefore, if Cookies are used by the publisher, your Browser settings will treat the Cookie as first party Cookie.  As used herein “Cookie” means a small piece of information that is placed on your device’s Browser while you are viewing a website or using the Conduit Software, the Customized Software and/or the Third Party Software. Some of the Third Party Software may pop-up on the screen of your computer and/or mobile device.  Because Customized Software is installed on your computer, the Customized Software takes up storage space on your hard-drive.  The amount of storage space will vary based on the size of the Customized Software and any Third Party Software available to you from it.  Some of the data stored in this storage space may include your personal information.  Please review the policies of the Third Party’s and/or Publishers for information about their practices.  </ol><br><br>
        <ol><b>2.3.</b>	Third Party Software will have their own terms and conditions and privacy policies and we urge you to review them prior to using them as your use of such Third Party Software is subject to these terms and conditions and privacy policies. Third Party Software is not owned by Conduit.  Conduit is not responsible for any Third Party Software and you acknowledge that Third Party Software may be modified or removed by its respective content owners at any time. You assume all responsibility and risk of use of any Third Party Software and Conduit hereby disclaims any and all liability to you or any third party related thereto. Conduit does not have any obligation to examine or scan Third Party Software, for any purpose, and is not responsible for the accuracy, completeness, appropriateness or legality of any Third Party Software. The fact that a Third Party Software is available via the Conduit Platform or otherwise is not an endorsement, authorization or representation of Conduit's affiliation with any third party, nor is it an endorsement of such Third Party Software and you hereby waive any legal or equitable rights or remedies you have or may have against Conduit with respect thereto. </ol><br><br>
        <ol><b>2.4.</b>	In addition, Conduit, as a platform provider, provides Publishers and other third parties with a large number of tools to enable them to create interesting and unique apps, buttons and gadgets that they may distribute to you.  Some of these tools may give these third parties the ability to access, collect, store and/or share your information. As Conduit is merely the provider of the technology and these third parties are using it and making it available to you, such apps, buttons and gadgets are also considered as Third Party Software.</ol> <br><br>
        3.	<b>License to Software and Use.</b><br>
        <ol><b>3.1.</b>	Conditioned upon your compliance with the terms and conditions of this EULA, Conduit hereby grants to you a limited, reversible, non-exclusive, personal, non-sublicensable, non-transferable, non-assignable license to install and use the executable form of the Conduit Software on a single computer or device (whether mobile device or other), solely for your personal use, provided that you use the Conduit Software on a computer, device (whether mobile device or other) owned or controlled by you. You may make a single copy of the Conduit Software for backup purposes.  Conduit reserves all rights in the Conduit Software not expressly granted to you in this EULA. </ol><br><br>
        <ol><b>3.2.</b>	With respect to any Third Party Software that may be incorporated with or into any Conduit Software, you acknowledge and agree that your use of such Third Party Software shall also be subject to its respective usage and privacy terms. </ol><br><br>
        <ol><b>3.3.</b>	As part of the installation process of the Customized Software, you may be changing your Browser settings and/or have the ability to opt to add certain changes to your Internet Browser settings and/or your mobile device settings and/or your social network account settings. By installing the Customized Software, you agree you have approved such changes and you understand you can reconfigure such settings at any time from the "Options Menu" available in the Customized Software, in the configuration options available on your Internet Browser and/or in your mobile device or from within your social network account. Such changes may include, without limitation, the following: <br>

            <ol><b>3.3.1.</b> Change of the default search engine in your Internet Browser's built-in search box, if applicable;<br>
                <b>3.3.2.</b> Change of the default Homepage and/or New Tabs of your Internet Browser, if applicable; <br>
                <b>3.3.3.</b> Addition of alternative "Page not Found" functionality, if applicable; <br>
                <b>3.3.4.</b> Additional search related services; <br>
                <b>3.3.5.</b> Allowing software updates of the Conduit Software once a new version is released and the ability to send notifications. <br>
                <b>3.3.6.</b> Allowing Conduit access to location-based information. <br>
                <b>3.3.7. </b> Allowing Conduit access to information contained on your Social Network account and/or site (which you must explicitly and separately opt in to). <br>
                <b>3.3.8.</b> Allow first party publisher Cookies to be installed in your Browser, which Cookies can be controlled through your Settings on your Browser Controls. </ol></ol><br><br>
        <ol><b>3.4.</b>	To uninstall the Customized Software, you may use the standard uninstall procedures offered by your device's Operating System or your Internet Browser. <br><br>

            <u>For example:  </u><br>
            To uninstall the Customized Software from Firefox - access the “tools” link from your Browser, go to “options” to find the Customized Software in the “add-ons” list and delete it. <br><br>

            To uninstall the Customized Software from your mobile device: please refer to your mobile device instructions manual or terms of service.  For example, on the Apple iPhone operating system, if you hold down the icon of the Customized Software you wish to delete until it shakes, you will get an “x” in the corner of the Customized Software icon and you can touch the “x” to delete the Software.  <br><br>

            Please note that the Customized Software may include one or more executable files, therefore if you wish to uninstall one or more Customized Software, please make sure to look for the specific Customized Software name in your computer or mobile device. </ol> <br><br>
        <ol><b>3.5.</b> You may not use the Customized Software in any manner that could: (i) damage, disable, overburden, or impair the Customized Software (or any server or networks connected to any the Customized Software), or (ii) interfere with any third party's use and/or enjoyment of the Customized Software (or any server or networks connected to the Customized Software). </ol><br><br>
        4.	<b>License Restrictions. </b><br>
        <ol><b>4.1.</b>	Except as expressly specified in this EULA, you may not: (a) copy or modify the Conduit Software; (b) transfer, sublicense, lease, lend, rent or otherwise distribute the Conduit Software to any third party; or (c) use the Conduit Software in any unlawful manner, for any unlawful purpose, or in any manner inconsistent with this EULA. You acknowledge and agree that portions of the Conduit Software, including, without limitation, the source code and the specific design and structure of individual modules or programs, constitute or contain trade secrets of Conduit and its licensors. Accordingly, you agree not to disassemble, decompile or otherwise reverse engineer any components of the Conduit Software provided in object code or any other Conduit products or services, in whole or in part, or permit or authorize a third party to do so, except to the extent such activities are expressly permitted by law notwithstanding this prohibition. </ol><br><br>
        <ol><b>4.2.</b>	Any Open Source Software that may be accompanying the Conduit Software is provided to you under the terms of the open source license agreement or copyright notice accompanying such Open Source Software or in the open source licenses file accompanying the Software. As used herein "<b>Open Source Software</b>" mean open source software components provided with the Conduit Software that are licensed to you under the terms of the applicable license agreements included with such open source software components or other materials for the Conduit Software. This EULA does not apply to any Open Source Software accompanying the Conduit Software and Conduit hereby disclaims any and all liability to you or any third party related thereto. </ol><br><br>
        5.	<b>Updates; Additional Services; Tests. </b><br>
        <ol><b>5.1.</b>	The Conduit Software may automatically download and install updates from Conduit, from time to time. These updates are designed to improve, enhance and further develop the Conduit Software and may take the form of bug fixes, enhanced functions, new software modules and completely new versions. You agree to receive such updates (and permit Conduit to deliver these to you) as part of your use of the Conduit Software. </ol><br><br>

        <ol><b>5.2.</b>	Further, you agree that by using the Conduit Software you may periodically send technical data and related information to Conduit to facilitate the provision of updates, product support and other services to you, if any, related to the Conduit Software.  Such information may include, but is not limited to, technical information or personal preferences about your computer or device (whether mobile device or other), and/or internet Browser and/or system.  Additionally, you agree Conduit may conduct A/B testing and change the look and feel of the Conduit Software or add additional features in order to improve your experience with the Conduit Software.  </ol><br><br>

        <ol><b>5.3.</b>	Your only recourse if you are unhappy with any of the modifications to the Conduit Software is to uninstall the Customized Software. </ol><br><br>
        6.	<b>Proprietary Rights.  </b><br>
        <ol><b>6.1.</b>	The Conduit Software is licensed, not sold to you. You acknowledge and understand that Conduit owns all right, title and interest in and to the Software, including without limitation all intellectual property rights therein. The Conduit Software is protected by United States (and other countries) copyright, trademark, other statutory and common law and international treaties. You will not delete or in any manner alter the copyright, trademark, and other proprietary rights notices or markings appearing on the Conduit Software as delivered to you. </ol><br><br>

        <ol><b>6.2.</b>	All rights in the Third Party Software, including all ownership rights are reserved and remain with such third parties. You agree that such third parties may enforce their rights against you directly in their own name. Conduit is not liable for your failure to comply with any applicable local, state, national and foreign laws, treaties and regulations or any contracts, rules, policies or procedures applicable to your use of any Third Party Software. </ol><br><br>
        7.	<b>Privacy and Legal Rights </b><br>
        <ol><b>7.1.</b>	The Conduit Privacy Policies (available at <a href="http://www.conduit.com/privacy">http://www.conduit.com/privacy</a>) contain information about Conduit's data protection policies and explains how Conduit accesses, collects, uses and/or shares information that is generated by your use of the Customized Software.  You consent to Conduit’s use of your data in accordance with Conduit's Privacy Policies. </ol><br><br>

        <ol><b>7.2.</b>	Conduit collects search query information.  Such search query information could be used to serve relevant ads to you and/or to monitor the performance of the search services.  </ol><br><br>

        <ol><b>7.3.</b>	Conduit prohibits the violation of a user's privacy rights and the distribution of materials that are illegal, infringing or may be deemed offensive by Conduit, in its sole discretion, as part of its terms of service and user agreements. If you believe that your legal or privacy right has been violated while using the Customized Software or Third Party Software, Conduit encourages you to report such matters to Conduit at your earliest convenience (to report, please visit the "Legal" section at the Conduit website, at <a href="http://www.conduit.com/">http://www.conduit.com/</a>). Conduit will, at its discretion, examine your complaint and take commercially reasonable efforts to attempt to resolve the issue as part of Conduit's commitment to providing a positive user experience. </ol><br><br>
        8.	<b>Your Obligations. </b><br>
        <ol><b>8.1.</b>	You hereby acknowledge and agree to only use the Conduit Software as permitted in this EULA. </ol><br><br>

        <ol><b>8.2.</b>	You agree to comply with all applicable laws, rules and regulations when using the Customized Software.  You will not use the Customized Software to infringe anyone's rights, including, without limitation, any intellectual property rights of any person or entity. </ol><br><br>

        <ol><b>8.3.</b>	You agree that you are solely responsible for (and that Conduit has no responsibility to you or to any third party) your use of the Customized Software, any breach of your obligations under the EULA, and for the consequences (including any loss or damage which Conduit may suffer) of any such breach.</ol><br><br>
        9.	<b>No Obligation.  </b><br>
        Conduit is not obligated to maintain or support the Conduit Software, or to provide you with updates, fixes, or services related thereto. You understand that during and/or by using the Customized Software, you may encounter Third Party Software that may be deemed offensive, indecent or objectionable.  Nevertheless, you agree to use the Customized Software at your own risk and that Conduit shall not have any liability to you with respect to such content.  <br><br>
        10.	 <b>Government Users.  </b><br>
        Any use, duplication, or disclosure of the Customized Software by the U.S. government is subject to the restrictions as set forth in this Agreement and as provided in DFARS 227.7202-1(a) and 227.7202-3(a) (1995), DFARS 252.227-7013(c)(1)(ii) (OCT 1988), FAR 12.212(a) (1995), FAR 52.227-19, or FAR 52.227-14 (ALT III), as applicable.  Manufacturer is Conduit Ltd. <br><br>
        11.	 <b>Export Laws.  </b><br>
        <ol><b>11.1.</b>	You agree to comply fully with all U.S. export laws and regulations to ensure that neither the Customized Software nor any technical data related thereto nor any direct product thereof are exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations.  Furthermore, you agree you will not export nor re-export the Customized Software nor any technical data related thereto nor any direct product thereof to any US embargoed country.  </ol><br><br>

        <ol><b>11.2.</b>	By downloading and using the Customized Software, you further represent and warrant that: (a) you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a "terrorist supporting" country; and (b) you are not listed on any U.S. Government list of prohibited or restricted parties. </ol><br><br>
        12.	 <b>Disclaimer of Warranties. </b><br>
        In addition to the limitations of Conduit’s liability expressly contained in this Agreement, Conduit further disclaims any warranty related to acknowledge and agree that you assume all the responsibility and risk for your use of the Software and the results and performance thereof and your use of any Third Party Software. THE CONDUIT SOFTWARE IS PROVIDED TO YOU ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTY OF ANY KIND.  CONDUIT DISCLAIMS ALL WARRANTIES AND CONDITIONS, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO ANY IMPLIED WARRANTIES AND CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT, AND ANY WARRANTIES AND CONDITIONS ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE.  NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED FROM CONDUIT OR ELSEWHERE WILL CREATE ANY WARRANTY OR CONDITION NOT EXPRESSLY STATED IN THIS AGREEMENT.  CONDUIT DOES NOT REPRESENT OR WARRANT THAT: (I) THE CONDUIT SOFTWARE OR ANY THIRD PARTY SOFTWARE WILL MEET YOUR REQUIREMENTS OR WILL BE ERROR FREE OR THAT ANY ERRORS WILL BE CORRECTED; (II) THE OPERATION OF THE CONDUIT SOFTWARE OR ANY THIRD PARTY SOFTWARE WILL BE UNINTERRUPTED; OR (III) THE ACCURACY, TIMELINESS, COMPLETENESS, OR ADEQUACY OF THE CONDUIT SOFTWARE, ANY THIRD PARTY SOFTWARE AND ANY DATA ACCESSED THEREFROM. INFORMATION PROVIDED THROUGH THE CONDUIT SOFTWARE OR ANY THIRD PARTY SOFTWARE, INCLUDING WITHOUT LIMITATION, WEATHER REPORTS, FINANCIAL DATA, ANALYSIS, MARKET INFORMATION AND NEWS,  MAY BE DELAYED, INACCURATE, OR CONTAIN ERRORS OR OMISSIONS, AND THE CONDUIT GROUP (DEFINED BELOW) AND CONDUIT'S THIRD PARTY LICENSORS WILL HAVE NO LIABILITY WITH RESPECT THERETO. CONDUIT MAY CHANGE OR DISCONTINUE ANY ASPECT OR FEATURE OF THE CONDUIT SOFTWARE OR THE USE OF ALL OR ANY FEATURES OR TECHNOLOGY IN THE CONDUIT SOFTWARE OR THE THIRD PARTY SOFTWARE AT ANY TIME WITHOUT PRIOR NOTICE TO YOU. YOUR ONLY RIGHT OR REMEDY WITH RESPECT TO ANY PROBLEMS OR DISSATISFACTION WITH THE CONDUIT SOFTWARE IS TO UNINSTALL AND CEASE USE OF THE CUSTOMIZED SOFTWARE. SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF CERTAIN WARRANTIES, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU. <br><br>
        13.	 <b>Limitation of Liability. </b><br>
        IN NO EVENT WILL CONDUIT, ITS AFFILIATED ENTITIES OR ANY OF THEIR RESPECTIVE OFFICERS, DIRECTORS, EMPLOYEES OR AUTHORIZED AGENTS (COLLECTIVELY, THE "CONDUIT GROUP") AND CONDUIT'S THIRD PARTY LICENSORS BE LIABLE TO YOU FOR ANY SPECIAL, INDIRECT, INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOST DATA, LOST PROFITS, LOSS OF GOODWILL, LOST REVENUE, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE OR COSTS OF PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES, ARISING OUT OF OR IN CONNECTION WITH THIS EULA OR THE INSTALLATION OR USE OF OR INABILITY TO USE THE CONDUIT SOFTWARE OR ANY THIRD PARTY APPLICATION UNDER ANY THEORY OF LIABILITY, INCLUDING BUT NOT LIMITED TO CONTRACT OR TORT (INCLUDING PRODUCTS LIABILITY, STRICT LIABILITY AND NEGLIGENCE), AND WHETHER OR NOT THE CONDUIT GROUP OR ITS THIRD PARTY LICENSORS WERE OR SHOULD HAVE BEEN AWARE OR ADVISED OF THE POSSIBILITY OF SUCH DAMAGE AND NOTWITHSTANDING THE FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY STATED HEREIN.  NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL CONDUIT'S AGGREGATE LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATED TO THIS EULA, TO THE FULLEST EXTENT POSSIBLE UNDER APPLICABLE LAW, EXCEED THE AMOUNT PAID, IF ANY, BY YOU FOR THE CONDUIT SOFTWARE. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF LIABILITY, SUCH AS FOR INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION OR EXCLUSION MAY NOT APPLY TO YOU. <br><br>
        14.	 <b>Indemnification.</b><br>
        To the maximum extent permitted by law, You agree to defend, indemnify and hold the Conduit Group harmless from and against any and all claims, suites, losses, liability, costs or expenses (including but not limited to reasonable attorneys fees) arising from or incurred as a result of your use of the Customized Software, including your downloading, installation, or use of the Customized Software, or your violation of this EULA. <br><br>
        15.	 <b>Term and Termination. </b><br>
        Your license to use the Conduit Software under this EULA shall continue until it is terminated by either party. You may terminate this EULA at any time, by discontinuing the use of all or any of the Customized Software and by destroying all copies of the Customized Software in your possession and control. This EULA and the license granted to you under this EULA will terminate automatically if you breach any term of this EULA. Upon termination, you must at Conduit's option either promptly destroy or return to Conduit all copies of the Customized Software in your possession or control. Sections  2, 3, 4, 6 through 12, 14 and 16 shall survive the termination of this EULA. <br><br>
        16.	 <b>Miscellaneous. </b><br>
        (a) This EULA and all the policies referenced herein constitute the entire agreement between Conduit and you concerning the subject matter hereof, and it may only be modified by a written amendment signed by an authorized executive of Conduit. (b) The section titles in this EULA are provided solely for convenience and have no legal or contractual significance. (c) This EULA shall be governed by and interpreted under the laws of the State of New York, without regard to its conflicts of laws provisions. All actions relating to this EULA and the Customized Software shall be brought in the competent court in the State of New York. The United Nations Convention on Contracts for the International Sale of Goods is expressly excluded. Notwithstanding this, you agree that Conduit will still be allowed to apply for injunctive remedies (or an equivalent type of unilateral, non-monetary urgent legal relief) in any jurisdiction. (d) The failure of either party to enforce any rights granted hereunder or to take action against the other party in the event of any breach hereunder shall not be deemed a waiver by that party as to subsequent enforcement of rights or subsequent actions in the event of future breaches. (e) If for any reason a court of competent jurisdiction finds any provision of his EULA or portion thereof, to be unenforceable, that provision of this EULA shall be enforced to the maximum extent permissible so as to affect the intent of the parties, and the remainder of this EULA shall continue in full force and effect. Conduit reserves the right, at our discretion, to update or revise this EULA. (f) Except as required by law, the controlling language of this EULA is English. In the event of inconsistency or discrepancy between the English version and any other language version, the English language version shall prevail. (g) You may not assign your rights under this EULA to any party without Conduit's consent. (h) If any provision of this EULA shall be deemed unlawful, void or for any reason unenforceable, then that provision shall be deemed severable from this EULA and shall not affect the validity and enforceability of any remaining provisions. (i) Nothing in this EULA will be construed as creating a joint venture, partnership, employment or agency relationship between you and Conduit, and you do not have any authority to create any obligation or make any representation on Conduit's behalf. (j) If you have any questions about the Software, please visit our website at <a href="http://www.conduit.com/">http://www.conduit.com/</a>.  <br><br>
        17.	 <b>Third Party Beneficiaries.</b><br>
        Please note that when accessing the Customized Software you may also be subject to the terms of use of other third parties.   You acknowledge that third party application marketplaces (including but not limited to the Apple App Store, the Google Android Marketplace, the Microsoft Windows Phone 7 Marketplace) may be third party beneficiaries of this EULA and upon your acceptance of this EULA such stores or marketplaces may have the right to enforce this EULA against you as a third party beneficiary .  You further acknowledge and agree that such parties are not parties to this EULA other than as third party beneficiaries and are not responsible for providing maintenance and support services with respect to the Software.  <br><br>
        18.	 <b>Software Questions, Comments, and Contact Information.</b><br>
        If you have any questions, complaints and/or claims, you may contact Conduit at:<br>
        Conduit <br>
        950 Tower Lane<br>
        Suite 1755 <br>
        Foster City, CA 94404<br>
        E-mail: <a href="mailto:support@conduit.com">support@conduit.com </a><br><br>
        <p>
            Last updated: July 12, 2012
        </p>
        <p>
            <strong>Additional Third Party Licenses</strong><br>This <a href="http://smartbar.webapps.conduitapps.com/MICROSOFT SOFTWARE LICENSE TERMS.docx">license</a> governs your use of the Windows Media Player Firefox Plug-In.
        </p>
        <div>
            <span id="extraEula"></span>
        </div>
        <br>
    </ol>

		</div>

		<div class="dashboard-bottom"></div>
	</div>

	<? $contactus_domain='pdfssoftware.com'; include('/var/www/vhosts/common/include/contactlib_addr.php'); ?>

	<div class="footer">
		<a href="#" onclick="show_cont();return false;">Contact Us</a>&nbsp;&nbsp;
		|&nbsp;&nbsp;<a href="/privacypolicy.php">Privacy Policy</a>
	</div>

	<div class="clear"></div>

</div>
</body>
</html>
